// ignore_for_file: ant_identifier_names

import 'package:flutter/material.dart';
import 'package:flutter_tdd/core/constants/enum_extension/enum_factory_extension.dart';
import 'package:flutter_tdd/features/contract/presentation/pages/contract_screen/contract_screen_imports.dart';
import 'package:flutter_tdd/features/maintenance/presentation/pages/maintenance_screen/maintenance_screen_imports.dart';
import 'package:flutter_tdd/features/owner_properties/presentation/pages/owner_properties/owner_properties_imports.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

@JsonEnum(valueField: 'value')
enum AccessPages {
  USERS("users"),
  ACL_ACTIONS("acl_actions"),
  ACL_ROLES("acl_roles"),
  ACL_STATUS("acl_status"),
  ACL_LINKS("acl_links"),
  ALERTS_TEMP("alerts_temp"),
  ALERTS_TYPES("alerts_types"),
  LANG("lang"),
  ACL_PAGE("acl_page"),
  UTILITY("utility"),
  SETTINGS("settings"),
  HOME("home"),
  ACL_FIELD("acl_field"),
  ACL_TABLE("acl_table"),
  ACL_TAX("acl_tax"),
  CHART("chart"),
  PAYMENT_TERM("payment_term"),
  PRODUCTS("products"),
  PRODUCT("product"),
  SETUP("setup"),
  INDEX("index"),
  PRICELIST("pricelist"),
  INTEGRATION("integration"),
  PARTNER("partner"),
  ATTACHMENT("attachment"),
  CRM_LEAD("crm_lead"),
  PRODUCT_ATTRIBUTE("product_attribute"),
  SEQUENCE("sequence"),
  WEBSITE_LIST("website_list"),
  WEBSITE_PAGE("website_page"),
  WEBSITE_MENU("website_menu"),
  WEBSITE_BULK("website_bulk"),
  ACTIVITY_TYPE("activity_type"),
  SALE_ORDER("sale_order"),
  ACTIVITY("activity"),
  CRM("crm"),
  CRM_PIPELINE("crm_pipeline"),
  PAYMENT_ACQUIRER("payment_acquirer"),
  ALERT("alert"),
  IR_VIEW("ir_view"),
  IR_MODULE("ir_module"),
  MODULE_SETUP("module_setup"),
  BCYP("bcyp"),
  AM_VEHICLE("am_vehicle"),
  AM_BORAD("am_borad"),
  AM_CPNT("am_cpnt"),
  AM_JOB("am_job"),
  AM_WSP("am_wsp"),
  FORM("form"),
  CRM_CAMP("crm_camp"),
  CRM_LIST("crm_list"),
  AM_TRANSIT("am_transit"),
  RES_CAL("res_cal"),
  RES_LIST("res_list"),
  RES_REMIND("res_remind"),
  RES_REMIND_LIST("res_remind_list"),
  BACKUPS("backups"),
  ROOT_MAINT("root_maint"),
  PLT_MAINT("plt_maint"),
  IR_AUTOBOT("ir_autobot"),
  IR_CRON("ir_cron"),
  IR_UOM("ir_uom"),
  IR_TRIGGER("ir_trigger"),
  IR_ML("ir_ml"),
  PLT_SUPER("plt_super"),
  PLT_LIMIT("plt_limit"),
  RES_MEDIA("res_media"),
  RES_ICON("res_icon"),
  ACL_TAB("acl_tab"),
  ACL_VIEW("acl_view"),
  ACL_POLICY("acl_policy"),
  USER_TYPE("user_type"),
  AM_OWNER("am_owner"),
  AM_ROLE("am_role"),
  SER_UPDATE("ser_update"),
  ACCESS_POLICY("access_policy"),
  RES_ROLE("res_role"),
  AM_PAY("am_pay"),
  BACKUP_DEST("backup_dest"),
  CRM_SETUP("crm_setup"),
  SHOP("shop"),
  SHP_CAT("shp_cat"),
  SHP_ITM("shp_itm"),
  PLT_TASK("plt_task"),
  PLT("plt"),
  PLT_PROP("plt_prop"),
  PLT_VAL("plt_val"),
  PLT_MYO("plt_myo"),
  PLT_ATTR("plt_attr"),
  PLT_TTS("plt_tts"),
  PLT_SRV("plt_srv"),
  PLT_TPL("plt_tpl"),
  PLT_SETUP("plt_setup"),
  PLT_REPORT("plt_report"),
  PLT_EXP("plt_exp"),
  PLT_COMB("plt_comb"),
  PLT_EINV("plt_einv"),
  PLT_EVAC("plt_evac"),
  RES_CLIENT("res_client"),
  RES_IMP("res_imp"),
  RES_INDUSTRY("res_industry"),
  RES_CLAIM("plt_claim"),
  RES_GROUP("res_group"),
  ACC_TREASURY("acc_treasury"),
  ACC_ACCOUNT("acc_account"),
  ACC_TRANS("acc_trans"),
  ACC_SET("acc_set"),
  ACC_CENT("acc_cent"),
  ACC_JOURNAL("acc_journal"),
  ACC_PAYORDER("acc_payorder"),
  PLT_PAY("plt_pay"),
  FINANCE("finance"),
  EINVOICE("einvoice"),
  IR_ATT("ir_att"),
  ACC_REPORT("acc_report"),
  CRM_REPORT("crm_report"),
  ACC_BRANCH("acc_branch"),
  ACTIVITY_RESPONSE("activity_response"),
  PLT_RENEW("plt_renew"),
  PLT_QUOTE("plt_quote"),
  SSRV("ssrv"),
  SS_OWNER("ss_owner"),
  TRASH("trash"),
  SS_TENANT("ss_tenant"),
  REM("rem"),
  REM_FOLLOW("rem_follow"),
  REM_BROKERAGE("rem_brokerage"),
  REM_PORTAL("rem_portal"),
  REM_LISTING("rem_listing"),
  CRM_QUOTE("crm_quote"),
  NTF_RULE("ntf_rule"),
  NTF_PUSH("ntf_push"),
  WQF("wqf"),
  WQF_HEIR("wqf_heir"),
  WQF_DIST("wqf_dist"),
  WQF_CHARITY("wqf_charity"),
  WQF_YIELD("wqf_yield"),
  WQF_SUPER("wqf_super"),
  WQF_JUEL("wqf_juel"),
  EJAR_AUTH("ejar_auth"),
  EJAR("ejar"),
  EJAR_PROP("ejar_prop"),
  EJAR_UNIT("ejar_unit"),
  EJAR_CONTR("ejar_contr"),
  EJAR_ENT("ejar_ent"),
  PLT_PROP_VAC("plt_prop_vac"),
  PLT_TTS_ARCH("plt_tts_arch"),
  ACC_SETUP("acc_setup"),
  CURRENCY("currency"),
  ACC_RECUR("acc_recur"),
  ACC_PERIOD("acc_period"),
  ACC_FISCAL("acc_fiscal"),
  WH_QUOTE("wh_quote"),
  CRM_SCRAPE("crm_scrape"),
  CMS_PROJECT("cms_project"),
  CMS_META("cms_meta"),
  CMS("cms"),
  API_CRED("api_cred"),
  API_UNIT("api_unit"),
  CRM_ACTIVITY("crm_activity"),
  CRM_CONTACT("crm_contact"),
  ACC_MISC("acc_misc"),
  CCM_CDR("ccm_cdr"),
  CCM_TRX("acc_trx"),
  PLT_LICENSE("plt_license"),
  PLT_PROP_MTR("plt_prop_mtr"),
  PLT_PROP_MTR_INV("plt_prop_mtr_inv"),
  EJAR_DOCS("ejar_docs"),
  SER_PLAN("ser_plan"),
  CRM_DEMO("crm_demo"),
  ACC_MOVE_ERR("acc_move_err"),
  WH_SRV("wh_srv"),
  ZATCA_AUTH("zatca_auth"),
  PLT_CR_DR_NOTE("plt_cr_dr_note"),
  CRM_PERFORMANCE("crm_performance"),
  IR_ACTIVITY_FEEDBACK("ir_activity_feedback"),
  EJAR_STEP("ejar_step"),
  DEVELOPMENT("development"),
  WH_TICKET("wh_ticket"),
  PLT_OFFER("plt_offer"),
  EJAR_MAPPING("ejar_mapping"),
  non("");

  final String value;

  const AccessPages(this.value);

  factory AccessPages.fromValue(String val) {
    try {
      return AccessPages.values.enumFactory(val);
    } catch (_) {}
    return non;
  }

  Widget getPage() {
    if (this == AccessPages.SS_TENANT) {
      return const ContractScreen();
    } else if (this == AccessPages.PLT_MAINT) {
      return const MaintenanceScreen();
    } else if (this == AccessPages.SS_OWNER) {
      return const OwnerProperties();
    }
    return Container();
  }
}
